// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkhtthtyrldtaganhbim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBraHR0aHR5cmxkdGFnYW5oYmltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0OTAwNDAsImV4cCI6MjA3MzA2NjA0MH0.TgedUAbgzBFh0ZOMZbcR0K5-3uedrMK2QZdnTDwACeE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});